# Generated by Django 5.0.1 on 2024-01-31 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevator_speed', models.IntegerField()),
                ('number_of_floors', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='ElevatorCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_floor', models.IntegerField()),
                ('origin_floor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_started_at', models.DateTimeField()),
                ('movement_finished_at', models.DateTimeField()),
                ('origin_floor', models.IntegerField()),
                ('target_floor', models.IntegerField()),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator.elevator')),
                ('elevator_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator.elevatorcall')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator.person')),
            ],
        ),
        migrations.AddField(
            model_name='elevatorcall',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator.person'),
        ),
    ]
