# Generated by Django 5.0.1 on 2024-01-31 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevatorcall',
            name='elevator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elevator.elevator'),
            preserve_default=False,
        ),
    ]
