# Generated by Django 5.0.1 on 2024-01-31 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0002_elevatorcall_elevator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='elevator_call',
        ),
        migrations.DeleteModel(
            name='ElevatorCall',
        ),
    ]
