# Generated by Django 5.0.1 on 2024-01-31 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0003_remove_movement_elevator_call_delete_elevatorcall'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevatorCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_floor', models.IntegerField()),
                ('origin_floor', models.IntegerField()),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator.elevator')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator.person')),
            ],
        ),
        migrations.AddField(
            model_name='movement',
            name='elevator_call',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elevator.elevatorcall'),
            preserve_default=False,
        ),
    ]
