# Generated by Django 5.0.1 on 2024-02-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0004_elevatorcall_movement_elevator_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='current_floor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
