# Generated by Django 5.0.1 on 2024-02-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0005_elevator_current_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='movement_finished_at',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='movement_started_at',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='origin_floor',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='target_floor',
        ),
    ]
