# Generated by Django 5.0.1 on 2024-02-01 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0007_movement_avg_movement_speed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movement',
            old_name='total_movement_time',
            new_name='total_movement_time_ms',
        ),
        migrations.AlterField(
            model_name='movement',
            name='movement_finished_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 14, 4, 25, 809480)),
        ),
        migrations.AlterField(
            model_name='movement',
            name='movement_started_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 14, 4, 25, 809480)),
        ),
    ]
