# Generated by Django 5.0.1 on 2024-02-02 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0008_rename_total_movement_time_movement_total_movement_time_ms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='avg_movement_speed',
        ),
        migrations.AddField(
            model_name='movement',
            name='avg_movement_speed_floor_by_seconds',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='movement',
            name='movement_finished_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 23, 14, 13, 588851)),
        ),
        migrations.AlterField(
            model_name='movement',
            name='movement_started_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 23, 14, 13, 588851)),
        ),
    ]
