# Generated by Django 5.0.1 on 2024-02-02 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0009_remove_movement_avg_movement_speed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevator',
            name='elevator_speed',
        ),
        migrations.AddField(
            model_name='elevator',
            name='elevator_max_speed',
            field=models.FloatField(default=4),
        ),
        migrations.AlterField(
            model_name='movement',
            name='movement_finished_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 23, 21, 20, 859800)),
        ),
        migrations.AlterField(
            model_name='movement',
            name='movement_started_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 23, 21, 20, 859800)),
        ),
    ]
